# sonar-project.properties
sonar.projectKey=com.capone.af:MyWebApp
sonar.projectName=MyWebApp
sonar.projectVersion=1.0-SNAPSHOT
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/test-classes
sonar.sourceEncoding=UTF-8
